[project]
name = "logo-widget"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anywidget[dev]>=0.9.21",
    "marimo>=0.18.1",
    "traitlets>=5.14.3",
]
